
BOT_USERNAME = "questionnaire_unibot"
ADMIN_USERNAME = "@dnrvv"

CREATED_GUIDE_MESSAGE = ("Гайд: тут будет гайд...")
PASSED_GUIDE_MESSAGE = ("Гайд: тут будет гайд...")

TITLE_LENGTH = 30
QUESTION_LENGTH = 350
ANSWER_OPTION_LENGTH = 100
ANSWER_LENGTH = 2000

QE_ID_LENGTH = 10
QUESTION_ID_LENGTH = 20
ANSWER_OPTION_ID_LENGTH = 20
USER_ANSWER_ID_LENGTH = 20

MAX_QUESTIONS_QUANTITY = 15
MAX_ANSWERS_QUANTITY = 5
PASSED_BY_MINIMUM = 1
ANSWER_LETTERS = ["A", "B", "C", "D", "E", "F", "G"]
