version: '3.3'

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    environment:
      PG_PASSWORD: $PG_PASSWORD
    restart: always
    ports:
      - 5432:5432
    networks:
      - tg_bot
    volumes:
      - ./postgres:/var/lib/postgresql
    env_file:
      - ".env"
  tgbot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python bot.py
    restart: always
    env_file:
      - ".env"
    networks:
    - tg_bot
    depends_on:
      - db
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - $PWD/redis-data:/var/lib/redis

    ports:
      - "6379:6379"
    networks:
      - tg_bot
    restart: always

networks:
  tg_bot:
    driver: bridge