
BOT_USERNAME = "msu_talk_bot"
ADMIN_USERNAME = "@dnrvv"

QE_ID_LENGTH = 10
QUESTION_ID_LENGTH = 20
ANSWER_OPTION_ID_LENGTH = 20
USER_ANSWER_ID_LENGTH = 20

MAX_QUESTIONS_QUANTITY = 15
MAX_ANSWERS_QUANTITY = 5
PASSED_BY_MINIMUM = 1
ANSWER_LETTERS = ["A", "B", "C", "D", "E", "F", "G"]
